### ISSUE TITLE
run adb command after Espresso test (feature request ?)

### ISSUE THREAD

**Issue by hannesa2** [ReactiveCircus/android-emulator-runner#65] opened 2020-05-23 06:41 UTC
First of all, thank you for the action.

For example

      - name: Android Emulator test
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: 28
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew cAT

Sometimes a process crashes

> Starting 0 tests on test(AVD) - 9
> Tests on test(AVD) - 9 failed: Instrumentation run failed due to 'Process crashed.'

and I want to upload output of `adb logcat` , especial on a crash.

Does someone has a clue, how to do this ?
Or is this a simple feature request to run a custom command after action ?

Thank you

**Comment by ychescale9** [comment] 2020-05-23 06:50
The action supports multi-line script, e.g.

```
script: |
  ./gradlew connectedCheck
  adb logcat
```

**Comment by hannesa2** [comment] 2020-05-23 09:17
Yes, I tried it

      - name: Android Emulator test
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: 28
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: |
            ./gradlew cAT
            echo ${{ github.workspace }}
            ls ${{ github.workspace }} -la
            adb logcat -d > ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/logcat.txt
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: owncloudApp-Espresso-test-report
          path: ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/*

But when you look into job https://github.com/hannesa2/owncloud-android/pull/5/checks?check_run_id=701706066 you see, the command is fired **before** the `./gradlew cAT` is finished (when  I understood right). --> useless

**Comment by ychescale9** [comment] 2020-05-23 09:33
I think the commands you are referring to are just printed at the start of the action but not executed, due to the gradlew cAT command failing and the step finishing early. What happens if you move those commands to a separate if failure() step after the “Android Emulator year” step and before the upload-artifact step?

**Comment by hannesa2** [comment] 2020-05-24 05:18
> What happens if you move those commands to a separate if failure() step after the “Android Emulator test” step and before the upload-artifact step?

Sorry there is no point doing it, the emulator is killed in step **Android Emulator test**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3314607/82746277-2c28a700-9d8e-11ea-9902-b8ef0201022a.png">

any `adb` command will not work anymore.

To be honest, I see only a solution in _android-emulator-runner_ to separate processes in multi line scripts. But I'm to dump to do this, I guess @ychescale9 you are the right person !

**Comment by ychescale9** [comment] 2020-05-24 06:03
Right now the action will exit with a failure whenever the script throws a non-0 exit code. I guess we could instead cache the error and still have the action execute the rest of the scripts and throws the error at the end. But I think it's much better to just write a custom script to catch the error instead of having the action does this by default which is not the expected behavior for most people.

I just had a another look at your workflow and looks like you can just do the following?

```
script: |
  adb logcat -d > ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/logcat.txt
  ./gradlew cAT
```

**Comment by hannesa2** [comment] 2020-05-24 06:16
> I guess we could instead cache the error and still have the action execute the rest of the scripts and throws the error at the end. 

This is in my point of view the most elegant solution

> But I think it's much better to just write a custom script to catch the error 

Following this idea how can I use `${{ github.workspace }}` in a shell script ?

> ```
> script: |
>   adb logcat -d > ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/logcat.txt
>   ./gradlew cAT
> ```
Sorry, this adb logcat ... must be run **after** ./gradlew cAT and not **before**

**Comment by ychescale9** [comment] 2020-05-24 06:16
Sorry you need to continuously stream logcat in the background. Updated the snippet above.

**Comment by ychescale9** [comment] 2020-05-24 06:26
And if you just do:

```
adb logcat -c
adb logcat *:E -v color &
./gradlew connectedCheck
```

You'll be able to see the error logs from logcat since you started running `./gradlew connectedCheck` all from the console log without having to uploading and downloading them.

**Comment by hannesa2** [comment] 2020-05-24 06:45
> Sorry you need to continuously stream logcat in the background. Updated the snippet above.

That's a smart idea !

          script: |
            adb logcat > ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/logcat.txt &
            ./gradlew cAT

But it don't upload `logcat.txt` I've no clue why

https://github.com/hannesa2/owncloud-android/pull/5/checks?check_run_id=703292637

... now I try the second proposal with direct print to console

**Comment by hannesa2** [comment] 2020-05-24 06:51
Btw, this 
`./gradlew cAT || adb logcat -d > ${{ github.workspace }}/owncloudApp/build/reports/androidTests/connected/logcat.txt`
uploads the `logcat.txt `but then the job is always successful

**Comment by hannesa2** [comment] 2020-05-24 06:53
> And if you just do:
> 
> ```
> adb logcat -c
> adb logcat *:E -v color &
> ./gradlew connectedCheck
> ```
> 
> You'll be able to see the error logs from logcat since you started running `./gradlew connectedCheck` all from the console log without having to upload and download them.

Works !

https://github.com/hannesa2/owncloud-android/pull/5/checks?check_run_id=703314765

**Comment by ychescale9** [comment] 2020-05-24 07:05
Great! I haven't done `adb` for a while and I know there are a lot of things you can do like filtering the logs with tag etc.

**Comment by ychescale9** [comment] 2020-05-24 07:19
I'm going to close this issue now. Please feel free to re-open or create another one if you run into other issues 😃

**Closed by ychescale9** 2020-05-24 07:19 UTC

**Comment by hannesa2** [comment] 2020-05-24 07:48
Just for the records, this is the final way I go without color noise

          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew cAT

Thank you !
