### ISSUE TITLE
ConnectedCheck tests are failing (IOException)

### ISSUE THREAD

**Issue by dennisguse** [ReactiveCircus/android-emulator-runner#58] opened 2020-04-27 06:28 UTC
We are using for OpenTracks [1] the android-emulator-runner and so far it was working very nicely!
However, recently we implemented tests doing file system operations and these are failing on Github Actions while working locally.

# Details
We have PR (https://github.com/OpenTracksApp/OpenTracks/pull/194#partial-pull-merging) that adds test for file system operations that were not checked before.
Sadly this results in 
https://github.com/OpenTracksApp/OpenTracks/pull/194/checks?check_run_id=617933592
```
de.dennisguse.opentracks.content.provider.CustomContentProviderUtilsTest > testDeleteWaypoint_onlyOneWayPointWithPhotoUrl[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: java.io.IOException: open failed: ENOENT (No such file or directory)
	at de.dennisguse.opentracks.content.data.TestDataUtil.createWaypointWithPhoto(TestDataUtil.java:99)
```

Are there some limitations within the Android Emulator that prevents us from doing read/writing files?

# Github Actions configuration
```
#https://github.com/marketplace/actions/android-emulator-runner
name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew connectedCheck
```

[1] https://github.com/OpenTracksApp/OpenTracks/

**Comment by ychescale9** [comment] 2020-04-27 13:41
Hi. Thanks for the detailed report.

Looks like the tests pass for API 29?

Could you try to create a new API 21 / x86_64 system image locally and see if the tests pass?

I can see the `IOException` is thrown from `createWaypointWithPhoto`, but would you be able to add a simple test using Android APIs directly e.g. `Context.getFilesDir()` that reproduces this issue on API 21? This would be a lot easier for me to reproduce the issue without understanding your codebase.

Thanks!

**Comment by dennisguse** [comment] 2020-04-27 19:59
Locally, I just tried API 21 with x86_64 and it works.

I added the requested test and pushed it to a separate branch: https://github.com/OpenTracksApp/OpenTracks/tree/CIfail

Interestingly, `Context.getFilesDir()` is working: https://github.com/OpenTracksApp/OpenTracks/runs/623472641

PS: As a workaround I disabled API 21 on the master branch.
Nice that you spotted this! @ychescale9

**Comment by ychescale9** [comment] 2020-04-27 22:06
I read somewhere that you need to explicitly call `mkdir` before doing read / write. Might be worth trying.

I’m closing this now, please re-open if needed 😀

**Closed** 2020-04-27 22:06 UTC
Labels: question
