### ISSUE TITLE
Is there option to enable sdcard?

### ISSUE THREAD

**Issue by uziasferreirazup** [ReactiveCircus/android-emulator-runner#56] opened 2020-04-20 06:11 UTC
I get this error when run my test, I execute screen shot tests and get this error:
 Is your sdcard directory read-only?

**Comment by ychescale9** [comment] 2020-04-20 12:03
I haven't tested the action with sdcard / external storage. Would you be able to share the full error log, your CI workflow, your test that causes this issue (e.g. are you writing to external storage)?

We may need some additional action inputs for configuring sdcard as this can't be done in the custom `script` after the emulator is already running.

**Comment by uziasferreirazup** [comment] 2020-04-20 12:07
[logs_86.zip](https://github.com/ReactiveCircus/android-emulator-runner/files/4503326/logs_86.zip)
I used this library from facebook to execute tests: https://github.com/facebook/screenshot-tests-for-android

**Comment by ychescale9** [comment] 2020-04-20 12:15
Thanks. Does [this](https://github.com/facebook/screenshot-tests-for-android/issues/162#issuecomment-385088965) help?

**Comment by uziasferreirazup** [comment] 2020-04-20 17:31
Not, because I need execute these lines after create emulator and in your steps, you create emulator and run a script and kill after

**Comment by ychescale9** [comment] 2020-04-20 22:25
Please see my comment [here](https://github.com/ReactiveCircus/android-emulator-runner/issues/57#issuecomment-616842298).

So it works if you put everything in the `script` block?

**Comment by uziasferreirazup** [comment] 2020-04-22 03:54
Sorry about delay to answer you, I change my strategy, I created another emulator with API level 25(this resolve the error about sdcard),  but now I got another error about the screenshots there are not equal, like I set the profile "Nexus 5" but I don't what density the device was created, I think the machine create a device with different density

**Comment by uziasferreirazup** [comment] 2020-04-22 03:56
[logs_133.zip](https://github.com/ReactiveCircus/android-emulator-runner/files/4513710/logs_133.zip)
I sent my long, but I try many things like  I remove this line:              `emulator-options: "-no-window -skin 1080x1920"` in another workflow to test and continues the error

**Comment by ychescale9** [comment] 2020-04-22 05:31
Can you share your full workflow?

**Comment by uziasferreirazup** [comment] 2020-04-22 13:07
```
name: Beagle Android Pull Request

on:
    pull_request:
        branches: [master]
        paths:
            - 'android/**'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - uses: malinskiy/action-android/install-sdk@release/0.0.5
            - name: run screen shot tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 25
                arch: x86_64
                target: google_apis
                profile: Nexus 5
                emulator-options: "-no-window -skin 1080x1920"
                script: ./gradlew executeScreenshotTests
            - name: Install Fastlane
              run: bundle install
            - name: Run pr check
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: bundle exec fastlane android pull_request_verification
```

**Comment by ychescale9** [comment] 2020-04-22 13:57
Sorry I'm not familiar with the screen shot testing library.

First of all the `-skin` option is [deprecated](https://developer.android.com/studio/run/emulator-commandline), are you sure you need it?

Does the profile matter for these screenshot tests? When running locally, does it not work with any device profile?

Can you just archive the report, download it and see what the actual failure is?

**Comment by PabloMGrela** [comment] 2020-05-31 21:08
I'm facing same issue here. I'm using the Karumi shot library https://github.com/Karumi/Shot
The screenshot testing needs to run in same Android version, density screen and resolution each time.
In which device did you create your reference screenshots @uziasferreirazup ? You'll need to create them in a Nexus 5 with sames specs that the one you are creating in the action.

@ychescale9 it's suposed we can create external sd with mksdcard command BUT not on macOS Catalina (the one that is used by github actions).
I was checking the docs and maybe we can solve this when `create avd` it seems that you can add an sd when you create the avd:

>  -c --sdcard  : Path to a shared SD card image, or size of a new sdcard for
                 the new AVD.

Not sure if this will work.

**Comment by uziasferreirazup** [comment] 2020-05-31 23:39
@PabloMGrela when you resolve this problem, can you share the yml?

**Comment by ychescale9** [comment] 2020-06-01 06:11
Hi @PabloMGrela, thanks for reporting. Would you be able to share the full log.
? Are you only seeing this with certain API levels? I really want to be able to reproduce it so if there’s a minimum sample project with the screenshot testing library you’re using you could share that’d make it a lot easier for us to come up with a fix.

**Comment by PabloMGrela** [comment] 2020-06-01 08:11
@ychescale9 here is the action run https://github.com/PabloMGrela/kotlin_clean/runs/725448273?check_suite_focus=true is a public repo so I guess you can check it.
It's only happening with API > 25. 

@uziasferreirazup I was able to run the screenshot tests with this yaml https://github.com/PabloMGrela/kotlin_clean/blob/master/.github/workflows/grela-ci.yml and making the original screenshots in a Nexus 6 with API 25

**Comment by ychescale9** [comment] 2020-06-01 13:05
Thanks @PabloMGrela. I haven't looked at the repo closely but it sounds like something related to the inconsistent storage path on different API levels. Does [this](https://stackoverflow.com/a/3853814) help?

Are you getting the same error locally with the same system image?

This weekend I'll try to fork your project to see if there's anything we can do.

**Comment by ychescale9** [comment] 2020-06-01 13:14
I just found this from Shot's readme:

Keep in mind the screenshots library needs the ``WRITE_EXTERNAL_STORAGE`` permission. When testing a library, add this permission to the manifest of the instrumentation apk. If you are testing an application, add this permission to the app under test. To grant this permission you can create an ``AndroidManifest.xml`` file inside the ``androidTest`` folder. Here is an example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="<YOUR_APP_ID>.test"
    android:sharedUserId="<YOUR_APP_ID>.uid">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

</manifest>
```

**You'll have to add the same ``android:sharedUserId="<YOUR_APP_ID>.uid"`` configuration to your ``app/AndroidManfiest.xml`` file in order to let the testing APK write into the SDCard.**. If you don't do this, you can end up facing a weird error with this message while running your tests:

```
java.lang.RuntimeException: Failed to create the directory /sdcard/screenshots/com.example.snapshottesting.test/screenshots-default for screenshots. Is your sdcard directory read-only?
```
------------
Looks like you're missing `android:sharedUserId` in `AndroidManifest`?

**Comment by PabloMGrela** [comment] 2020-06-01 13:35
I already tried that @ychescale9, locally I need to setup the emulator to add the sd card. I did it with the avd manager, I'll try from command line, but it seems that by default the emulator has no external sd card to save the screenshots.

**Comment by ychescale9** [comment] 2020-06-01 13:50
Ok let me know how you go 😃

**Comment by PabloMGrela** [comment] 2020-06-04 20:05
I tried with this secuence:
`$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis;x86' -d "pixel_xl" --force
nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot > /dev/null 2>&1 &
`

And same error. I also tried adding the sdcard on creation command (-c 100M) and nothing.
`java.lang.RuntimeException: Failed to create the directory /sdcard/screenshots/com.grela.clean.test/screenshots-default for screenshots. Is your sdcard directory read-only?
`

After change the version to android-25, it worked.
I'll try to give write permissions to storage on API 29.

**Comment by uziasferreirazup** [comment] 2020-06-04 20:08
@PabloMGrela do you care about sharing your yml with android-25? 
I have the current issue like, I created any emulator in android studio and take the screenshot, after I create the same profile in with this plugin, but the screenshot is not equal

**Comment by PabloMGrela** [comment] 2020-06-04 21:18
> @PabloMGrela do you care about sharing your yml with android-25? 
> I have the current issue like, I created any emulator in android studio and take the screenshot, after I create the same profile in with this plugin, but the screenshot is not equal

Sure-> https://www.github.com/PabloMGrela/kotlin_clean/tree/master/.github%2Fworkflows

Are you able to make it work locally?

**Comment by PabloMGrela** [comment] 2020-06-05 08:10
Problem solved!
https://github.com/facebook/screenshot-tests-for-android/issues/162#issuecomment-528282299

So is not about the action, it's about project configuration.

**Comment by ychescale9** [comment] 2020-06-05 08:34
Great! So this is due to storage behavior changes after all 😂 .

Does it also work on API 26-28?

**Comment by PabloMGrela** [comment] 2020-06-05 14:55
Yep, there are no sd card issues with that fix 👍

**Comment by ychescale9** [comment] 2020-06-05 15:00
Ok thanks! Let's close this now as the sd card issues can be resolved as mentioned above.

@uziasferreirazup Let me know if you still need help with anything else:)

**Closed by ychescale9** 2020-06-05 15:00 UTC
Labels: question

**Comment by erikjhordan-rey** [comment] 2020-10-07 21:01
I know is a closed issue just in case someone is faced with the same issue (trying to save time). 

My solution was:

Use `  android:requestLegacyExternalStorage="true"` ([Needed for Android 10](https://github.com/facebook/screenshot-tests-for-android/issues/162#issuecomment-528282299) )

```xml

 <application
        android:name=...
        android:allowBackup=...
        android:requestLegacyExternalStorage="true"

```



**androidTest/AndroidManifest.xml**
```  xml 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="APP_ID.test"
    android:sharedUserId="APP_ID.uid">
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
</manifest>
```

**main/AndroidManifest.xml**

```  xml 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="APP_ID"
    android:sharedUserId="APP_ID.uid">
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
</manifest>
```
If you want to see an example https://github.com/erikjhordan-rey/ATP-Rankings-Hilt-Dagger
